### ISSUE TITLE
Weird output compared to v1

### ISSUE THREAD

**Issue by OmgImAlexis** [siddharthkp/bundlesize2#23]
```
➜  snoo-wrapped git:(main) ✗ ./node_modules/bundlesize/index.js 
 PASS  ./dist/snoo-wrapped.js: 10.59KB < maxSize 20KB (brotli) 

 PASS  ./dist/snoo-wrapped.js: 11.95KB < maxSize 20KB (gzip) 

 PASS  ./dist/snoo-wrapped.js: 55.61KB < maxSize 90KB (no compression) 

➜  snoo-wrapped git:(main) ✗ ./node_modules/bundlesize2/index.js

─ ./dist/snoo-wrapped.js
  ─ ./dist/snoo-wrapped.js    deduplicated  

─ ./dist/snoo-wrapped.js
  ─ ./dist/snoo-wrapped.js    deduplicated  

─ ./dist/snoo-wrapped.js
  ✔ ./dist/snoo-wrapped.js    55.61KB < 90 kB none  

  1 check passed
```

**Comment by siddharthkp** [comment]
Ah, good catch!

I deduplicate the filepath so that you can have one limit for dist/* and another for dist/main.js

I did not consider compression though! Will add that to the dedup function

**Comment by OmgImAlexis** [comment]
Any chance on "none" being changed back to "no compression" in the case where there are multiple variants?

**Comment by siddharthkp** [comment]
Yep, makes a lot of sense 👍

**Comment by siddharthkp** [comment]
Fixed in bundlesize@0.0.29

**Comment by OmgImAlexis** [comment]
@siddharthkp the fix is working. 👍 


For local is there any chance on going back to the old format?
The green "PASS" was easier to see than a single green tick. It also takes up 2 lines per item now.

I don't really see a reason why it was changed between versions to be honest.

```
─ ./dist/snoo-wrapped.js
  ✔ ./dist/snoo-wrapped.js    10.61KB < 20 kB brotli  

─ ./dist/snoo-wrapped.js
  ✔ ./dist/snoo-wrapped.js    11.97KB < 20 kB gzip  

─ ./dist/snoo-wrapped.js
  ✔ ./dist/snoo-wrapped.js    55.67KB < 90 kB no compression  

  3 checks passed
```

**Comment by siddharthkp** [comment]
> I don't really see a reason why it was changed between version 1 and 2 to be honest.

Mostly a matter of personal aesthetics to be honest. I like the new design more.

> It also takes up 2 lines per item now.

Yeah, that one's totally fair. It was built with looser rules in mind like this one: 

```
─ build/**/*.js
  ✔ build/chunks/chunk-ch0nk.js    270B < 300B gzip  
  ✔ build/vendor-ha5h.js           270B < 300B gzip  

  2 checks passed  
```

But I can see how that's annoying when it's just one item per rule. Might be nice to shrink the output if there are no wildcard based rules. How annoying would you say that is for you?
