### ISSUE TITLE
Allow a given bundle-size configuration/path/glob to aggregate the file sizes into one summation number

### ISSUE THREAD

**Issue by seanblonien** [siddharthkp/bundlesize2#32]
With this configuration,
```
{
  "path": "./dist/*.js",
  "maxSize": "3 kB"
}
```
instead of this
```sh
─ ./dist/*.js
  √ ./dist/index.js    91B < 3 kB gzip
  √ ./dist/types.js    65B < 3 kB gzip
  √ ./dist/utils.js    293B < 3 kB gzip
```
add a flag that outputs one path/glob summation for file size
```sh
─ ./dist/*.js
  √ ./dist/*.js   449B < 3 kB gzip
```

Here's a suggestion for that flag/interface for this option:
```
{
  "path": "./dist/*.js",
  "maxSize": "3 kB",
  "sum": true
}
```

**Comment by siddharthkp** [comment]
Thanks for taking the time!

Can you explain the motivation behind this feature? Where would you like to measure this and what would you do with the metric?

Context: In the past I have tried to shy away from summing up multiple files because the performance of a page depends a lot on the way the individual chunks are loaded on the page (split across pages, lazy loaded, etc.). In my opinion, total size of `dist/*.js` or `chunks/*.js` isn't a good metric to measure/optimise. (previous discussion: https://github.com/siddharthkp/bundlesize/issues/20)

**Comment by seanblonien** [comment]
Honestly, my thought was to just use this tool as a cross-platform tool for checking all file sizes via CLI, and the use case that comes to mind is file size checking for libraries/modules (what bundlephobia does but CLI, maybe something already exists but I'm already use this tool and love it so far), using this to compare file sizes via different projects or different versions of the same project (my enterprise client is converting Angular.js to React site and I'm curious to show them how much less file size there is in general, and having a max total size in certain parts of the project may be helpful so we don't fall into the same bad patterns again), and then just generally set file-size restrictions on a group of source code that matches a pattern (such as restricting the size of the contents in a folder, like a feature folder, or just restricting a folder from a certain upper limit size an encouraging subfolders to be created when that size is reached).

I think now after thinking about it, it's pretty clear that this is beyond the scope of calculating bundlesize. I think individual file/chunk sizes is definitely what you should optimize for, not an aggregate sum that doesn't mean anything. I just thought as an optional parameter, it wouldn't be that big of a deal and consumers of this library maybe find good use cases of wanting to put an upper limit on a group of files in their projects.

All these use cases were much more practical extensions of what this tool already does, and these use cases don't really relate to "bundlesize optimization" as much as they relate to other file size restriction activities, separate from the bundle. Clearly the name of the library denotes it's intention around bundle size, so maybe this functionality should live in another tool, but I thought it couldn't hurt because the library does a bulk of the work to enable this feature anyways.

**Comment by siddharthkp** [comment]
Thanks for your well thought out reply, I appreciate it 👍 

Yep, I'd like to keep bundlesize do just 1 thing, but please feel free to fork/clone and take the relevant bits to build the idea you're thinking of. Another related project that might be helpful to take from: https://github.com/siddharthkp/cost-of-modules
