### ISSUE TITLE
Error "HttpError: Invalid request" (Only 65535 characters are allowed; 68372 were supplied)

### ISSUE THREAD

**Issue by joshje** [siddharthkp/bundlesize2#7]
I was very excited to see `bundlesize2` now exists! We have a lot of JS files being built by our deployment process, and `bundlesize` was unable to generate a valid details link in GitHub (the URL was too long).

Unfortunately this version also has an error, perhaps related to the number of files being checked:

```bash
⚠️ Could not add check
 

 
        Something broke pretty bad!
 

 
        Please create an issue with this error message: HttpError: Invalid request.


 
Only 65535 characters are allowed; 68372 were supplied.
 ```

This was built with CircleCI. I've attached the full logs for your reference: [bundlesize2-error.log.txt](https://github.com/siddharthkp/bundlesize2/files/4965497/bundlesize2-error.log.txt)

**Comment by siddharthkp** [comment]
Wow that output is huge! I imagine getting a really long list of ✔ successful checks doesn't really help you 🤔 

Would it make sense to you if we show failed ones first, and then truncate the successful ones after a threshold

**Comment by joshje** [comment]
@siddharthkp yes, that'd be very helpful. 

I can imagine scenarios where a whole bunch of them would go red for a related reason (e.g. if something was imported to all of the source files). In which case, something like this will ensure we always get a status check delivered:
https://github.com/siddharthkp/bundlesize2/pull/8

Feel free to use that PR, or do something along those lines. Note I also set a maximum limit of `50` chars on the `rightpad(_, maxFileLength)` output so that the line never gets too long.

**Comment by joshje** [comment]
Closing as this is now resolved!
